# Generated by Django 5.2.3 on 2025-07-02 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_history_duration_alter_history_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='history',
            name='routine',
        ),
        migrations.AddField(
            model_name='history',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='sets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
