# Generated by Django 5.2.3 on 2025-07-03 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_remove_exercise_reps_remove_exercise_sets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='duration',
            new_name='durationMin',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='weight',
            new_name='weightKg',
        ),
    ]
