# Generated by Django 5.2.3 on 2025-07-03 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='duration',
        ),
    ]
