# Generated by Django 5.2.3 on 2025-07-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_remove_history_user_remove_routine_user_weigth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('weightKg', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Weigth',
        ),
    ]
